routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\FamilyController;
use \App\Http\Controllers\FamilyCardController;
use \App\Http\Controllers\DragController;
use \App\Http\Controllers\FamilyMemberController;
use \App\Http\Controllers\AidTypeController;
use \App\Http\Controllers\PackageController;
use \App\Http\Controllers\DivisionController;
use \App\Http\Controllers\DistrictController;
use \App\Http\Controllers\UpazilaController;
use \App\Http\Controllers\UnionController;
use \App\Http\Controllers\ItemController;
use \App\Http\Controllers\ItemTypeController;
use \App\Http\Controllers\LotItemAmountController;
use \App\Http\Controllers\InstitutionController;
use \App\Http\Controllers\BivagController;
use \App\Http\Controllers\DepartmentController;
use \App\Http\Controllers\UserController;
use \App\Http\Controllers\DealerController;
use \App\Http\Controllers\Report\ReportController;

//require_once('routes/api.php');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Route::get('/home', [HomeController::class, 'index'])->name('home');


Route::group(['middleware' => ['auth']], function () {
//    Route::get('/', [App\Http\Controllers\HomeController::class, 'cache_clear'])->name('cache_clear');

    //*  Families Route Section */
    Route::post('/families/import', [FamilyController::class, 'import'])->name('families.import');
    Route::post('/families/export', [FamilyController::class, 'export'])->name('families.export');
    Route::get('/families/sampledatadownload', [FamilyController::class, 'sampledatadownload'])->name('families.sampledatadownload');
    Route::post('/families/phoneDuplicateCheck', [FamilyController::class, 'phoneDuplicateCheck'])->name('families.phoneDuplicateCheck');
    Route::post('/families/nidDuplicateCheck', [FamilyController::class, 'nidDuplicateCheck'])->name('families.nidDuplicateCheck');
    Route::post('/families/getFamilyInfo', [FamilyController::class, 'getFamilyInfo'])->name('families.getFamilyInfo');

    Route::post('/family-members/import', [FamilyMemberController::class, 'import'])->name('family-members.import');
    Route::get('/family-members/sampledatadownload', [FamilyMemberController::class, 'sampledatadownload'])->name('family-members.sampledatadownload');
    Route::get('/family-members/shift/{familyId}/{memberId}', [FamilyMemberController::class, 'shift'])->name('family-members.shift');
    Route::post('/family-members/shiftDone', [FamilyMemberController::class, 'shiftDone'])->name('family-members.shiftDone');

    Route::get('family-card/pendingCards', [FamilyCardController::class, 'pendingCards'])->name('family-card.pendingCards');
    Route::post('family-card/generateCardNumbers', [FamilyCardController::class, 'generateCardNumbers'])->name('family-card.generateCardNumbers');
    Route::get('family-card/createCard/{id}/{download?}', [FamilyCardController::class, 'createCard'])->name('family-card.createCard');
    Route::get('family-card/printCards', [FamilyCardController::class, 'printCards'])->name('family-card.printCards');
    Route::post('family-card/chunkCards', [FamilyCardController::class, 'chunkCards'])->name('family-card.chunkCards');
    Route::post('family-card/printCards', [FamilyCardController::class, 'printCards'])->name('family-card.printCards');
    Route::post('packages/getPackageLists', [PackageController::class, 'getPackageLists'])->name('packages.getPackageLists');
    Route::post('packages/getAssignedPackageLists', [PackageController::class, 'getAssignedPackageLists'])->name('packages.getAssignedPackageLists');
    Route::get('packages/bulkAssignPackage', [PackageController::class, 'bulkAssignPackage'])->name('packages.bulkAssignPackage');
    Route::post('packages/saveBulkAssignPackage', [PackageController::class, 'saveBulkAssignPackage'])->name('packages.saveBulkAssignPackage');
    Route::post('packages/assignPackage', [PackageController::class, 'assignPackage'])->name('packages.assignPackage');
    Route::post('packages/unAssignPackage', [PackageController::class, 'unAssignPackage'])->name('packages.unAssignPackage');
    Route::post('item-types/getItemLists', [ItemTypeController::class, 'getItemLists'])->name('item-types.getItemLists');
    Route::post('packages/saveItem', [PackageController::class, 'saveItem'])->name('packages.saveItem');
    Route::post('bivag/bivagSelectAjaxList', [BivagController::class, 'bivagSelectAjaxList'])->name('bivag.bivagSelectAjaxList');
    Route::post('department/deptSelectAjaxList', [DepartmentController::class, 'deptSelectAjaxList'])->name('department.deptSelectAjaxList');
    Route::get('users/changePassword', [UserController::class, 'changePassword'])->name('users.changePassword');
    Route::post('users/updatePassword', [UserController::class, 'updatePassword'])->name('users.updatePassword');
    Route::get('lot-item-amount/add/{packageID}', [LotItemAmountController::class, 'add'])->name('lot-item-amount.add');
    Route::get('lot-item-amount/edit/{packageID}/{lotId}', [LotItemAmountController::class, 'edit'])->name('lot-item-amount.edit');
    Route::post('lot-item-amount/saveLot/{id?}', [LotItemAmountController::class, 'saveLot'])->name('lot-item-amount.saveLot');
    Route::post('dealers/resetPassword/{id}', [DealerController::class, 'resetPassword'])->name('dealers.resetPassword');
    Route::post('dealers/getDealerLists', [DealerController::class, 'getDealerLists'])->name('dealers.getDealerLists');
    Route::post('dealers/getDealerModuleLists', [DealerController::class, 'getDealerModuleLists'])->name('dealers.getDealerModuleLists');
    Route::post('dealers/saveDealer', [DealerController::class, 'saveDealer'])->name('dealers.saveDealer');
    Route::post('dealers/getAssignDealerList', [DealerController::class, 'getAssignDealerList'])->name('dealers.getAssignDealerList');
//    Route::get('users/profile', [UserController::class, 'profile'])->name('users.deptSelectAjaxList');
//    Route::get('users/profile', [UserController::class, 'profile'])->name('users.deptSelectAjaxList');

    //*  District Route Section */
    Route::post('district/districtSelectAjaxList', '\App\Http\Controllers\DistrictController@districtSelectAjaxList')->name('district.districtSelectAjaxList');    // Ajax District List

    //*  Upazila-- Route Section */
    Route::post('upazila/upazilaSelectAjaxList', '\App\Http\Controllers\UpazilaController@upazilaSelectAjaxList')->name('upazila.upazilaSelectAjaxList');    // Ajax Upazila List

    //*  Union Route Section */
    Route::post('union/unionSelectAjaxList', '\App\Http\Controllers\UnionController@unionSelectAjaxList')->name('union.unionSelectAjaxList');    // Ajax District List

    /* Report Route */
    Route::get('report/familyReport', [ReportController::class, 'familyReport'])->name('report.familyReport');
    Route::post('report/familySearchData', [ReportController::class, 'familySearchData'])->name('report.familySearchData');
    Route::post('report/exportFamilyReport', [ReportController::class, 'exportFamilyReport'])->name('report.exportFamilyReport');

    Route::get('report/aidReport', [ReportController::class, 'aidReport'])->name('report.aidReport');
    Route::post('report/aidSearchData', [ReportController::class, 'aidSearchData'])->name('report.aidSearchData');
    Route::post('report/aidSearchAidVsFamilyData', [ReportController::class, 'aidSearchAidVsFamilyData'])->name('report.aidSearchAidVsFamilyData');
    Route::post('report/aidSearchAidVsDealerData', [ReportController::class, 'aidSearchAidVsDealerData'])->name('report.aidSearchAidVsDealerData');
    Route::post('report/aidSearchAidVsPackageData', [ReportController::class, 'aidSearchAidVsPackageData'])->name('report.aidSearchAidVsPackageData');
    Route::post('report/exportAidReport', [ReportController::class, 'exportAidReport'])->name('report.exportAidReport');

    Route::get('report/packageReport', [ReportController::class, 'packageReport'])->name('report.packageReport');
    Route::post('report/packageSearchData', [ReportController::class, 'packageSearchData'])->name('report.packageSearchData');
    Route::post('report/exportPackageReport', [ReportController::class, 'exportPackageReport'])->name('report.exportPackageReport');

    Route::get('report/dealerReport', [ReportController::class, 'dealerReport'])->name('report.dealerReport');
    Route::post('report/dealerSearchData', [ReportController::class, 'dealerSearchData'])->name('report.dealerSearchData');
    Route::post('report/exportDealerReport', [ReportController::class, 'exportDealerReport'])->name('report.exportDealerReport');


    /* Cron Tasks Routes */
    Route::get('cron/test', [FamilyMemberController::class, 'cronTest'])->name('cron.cronTest');


    /*  Resource Route  */
    Route::resource('users', \App\Http\Controllers\UserController::class);
    Route::resource('roles', \App\Http\Controllers\RoleController::class);
    Route::resource('permissions', \App\Http\Controllers\PermissionController::class);
    Route::resource('families',FamilyController::class);
    Route::resource('drags',DragController::class);
    Route::resource('family-members',FamilyMemberController::class);
    Route::resource('aid-types',AidTypeController::class);
    Route::resource('packages',PackageController::class);
    Route::resource('divisions',DivisionController::class);
    Route::resource('districts',DistrictController::class);
    Route::resource('upazillas',UpazilaController::class);

app/Models/Division.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Division extends Model
{
    protected $fillable = [
        'name','bn_name', 'url', 'div_code',
    ];

    public function saveData($data)
    {
        foreach ($data->request as $key => $value) {
            if ($key != "_token") {
                $this->$key = $value;
            }
        }

        $this->save();
        return 1;
    }

    public function updateData($data)
    {
        $ticket = $this->find($data['id']);
        foreach ($data->request as $key => $value) {
            if ($key != "_token") {
                $ticket->$key = $value;
            }
        }

        $ticket->save();
        return 1;
    }


    public function districts()
    {
        return $this->hasMany(District::class,'division_id', 'id')->orderBy('name', 'ASC');
    }

}

resources/views/divisions/create.blade.php
@extends('layouts.app')
@section('content-header')
    <h3>{{ $page_title }}</h3>
@endsection
@section('title')
    {{ $page_title }}
@endsection

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="card card-default">
                <form class="" method="post" action="{{ route('divisions.store') }}">
                    @csrf
                    <div class="card-header">
                        <h3 class="card-title">{{ $page_title }}</h3>

                        <div class="card-tools">
                            @can('location-list')
                                <a class="btn btn-primary" href="{{ route('divisions.index') }}"> বিভাগের
                                    তালিকা</a>
                            @endcan
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>নাম(English) *</label>
                                    <input type="text" class="form-control" name="name" id="name"
                                           placeholder="বিভাগের নাম" required>
                                    <span class="help-inline col-xs-12 col-sm-7">
                                        @error('name')
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                            @enderror
                                    </span>
                                </div>
                                <!-- /.form-group -->
                                <div class="form-group">
                                    <label>কোড *</label>
                                    <input type="number" min="0" max="200" class="form-control" name="div_code" id="div_code"
                                           placeholder="" required>
                                    @error('div_code')
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <!-- /.form-group -->
                            </div>
                            <!-- /.col -->
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>নাম(বাংলা) *</label>
                                    <input type="text" class="form-control" name="bn_name" id="bn_name"
                                           placeholder="বিভাগের নাম" required>
                                    <span class="help-inline col-xs-12 col-sm-7">
                                        @error('bn_name')
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                            @enderror
                                    </span>
                                </div>
                                <!-- /.form-group -->

                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">সংরক্ষন</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

@section('custom_script')
    <script type="text/javascript">
        $(document).ready(function () {
            //Initialize Select2 Elements
            $('.select2').select2()

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            })

        });
    </script>
@endsection

resources/views/divisions/edit.blade.php
@extends('layouts.app')
@section('content-header')
    <h3>{{ $page_title }}</h3>
@endsection
@section('title')
    {{ $page_title }}
@endsection

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="card card-default">
                <form class="form-horizontal" method="POST" action="{{ route('divisions.update', $division->id) }}">
                    <input type="hidden" name="_method" value="PUT">
                    @csrf
                    <div class="card-header">
                        <h3 class="card-title">{{ $page_title }}</h3>

                        <div class="card-tools">
                            @can('location-list')
                                <a class="btn btn-primary" href="{{ route('divisions.index') }}"> বিভাগের তালিকা</a>
                            @endcan
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>নাম(English) *</label>
                                    <input type="text" class="form-control" name="name" id="name"
                                           placeholder="বিভাগের নাম" value="{{ $division->name }}" required>
                                    <span class="help-inline col-xs-12 col-sm-7">
                                        @error('name')
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                            @enderror
                                    </span>
                                </div>
                                <!-- /.form-group -->
                                <div class="form-group">
                                    <label>কোড *</label>
                                    <input type="number" min="0" max="200" class="form-control" name="div_code"
                                           id="div_code"
                                           placeholder="" value="{{ $division->div_code }}" required>
                                    @error('div_code')
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <!-- /.form-group -->
                            </div>
                            <!-- /.col -->
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>নাম(বাংলা) *</label>
                                    <input type="text" class="form-control" name="bn_name" id="bn_name"
                                           placeholder="বিভাগের নাম" value="{{ $division->bn_name }}" required>
                                    <span class="help-inline col-xs-12 col-sm-7">
                                        @error('bn_name')
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                            @enderror
                                    </span>
                                </div>
                                <!-- /.form-group -->

                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">সংরক্ষন</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

@section('custom_script')
    <script type="text/javascript">
        $(document).ready(function () {
            //Initialize Select2 Elements
            $('.select2').select2()

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            })

        });
    </script>
@endsection

resources/views/divisions/index.blade.php
@extends('layouts.app')
@section('content-header')
    <h3>{{ $page_title }}</h3>
@endsection
@section('title')
    {{ $page_title }}
@endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12  card-primary">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title"> {{ $page_title }} </h3>
                            <div class="float-sm-right">
                                @can('location-create')
                                    <a class="btn btn-primary" href="{{ route('divisions.create') }}"> নতুন বিভাগ
                                        তৈরী</a>
                                @endcan
                            </div>
                        </div>
                        <div class="card-body">
{{--                            <div>--}}
{{--                                @foreach ($nesteds as $nested)--}}
{{--                                    <x-nested-item :nestedItems="$nested" />--}}
{{--                                @endforeach--}}
{{--                            </div>--}}
                            <div class="table-responsive">
                                <table id="example1" class="table table-bordered table-striped data-table">
                                    <thead>
                                    <tr>
                                        <th>ক্রমিক নং</th>
                                        <th>বিভাগ(বাংলা)</th>
                                        <th>বিভাগ(ইংরেজী)</th>
                                        <th>বিভাগ কোড</th>
                                        <th width="280px">ব্যবস্থা</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('custom_script')
    <script type="text/javascript">
        $(document).ready(function () {
            $(document).on("click", "a.delete-division", function (ev) {
                ev.preventDefault();
                let url = $(this).attr("href");
                let id = $(this).attr("id");
                if (confirm("আপনি কি তথ্য মুছে ফেলতে চান?")) {
                    $.ajax({
                        type: 'DELETE',
                        url: url,
                        dataType: 'json',
                        headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                        data: {id: id, "_token": "{{ csrf_token() }}"},

                        success: function (data) {
                            if (data.status == 'success') {
                                window.location.reload();
                            } else if (data.status == 'error') {
                                window.location.reload();
                                // data.request->session()->flash('status', 'Task was successful!');
                            }
//                    data.request->session()->flash('status', 'Task was successful!');
//                    setInterval(function() {
//                    }, 5900);
                        },
                        error: function (data) {
                            window.location.reload();
                        }
                    });

                } else {
                    return false;
                }
            });

            $(function () {
                var table = $('.data-table').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: "{{ route('divisions.index') }}",
                    columns: [
                        {data: "id", name: "id"},
                        {data: 'bn_name', name: 'bn_name'},
                        {data: 'name', name: 'name'},
                        {data: 'div_code', name: 'div_code'},
                        {data: 'action', name: 'action', orderable: false, searchable: false},
                    ]
                });
            });

        });
    </script>
@endsection