routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\FamilyController;
use \App\Http\Controllers\FamilyCardController;
use \App\Http\Controllers\DragController;
use \App\Http\Controllers\FamilyMemberController;
use \App\Http\Controllers\AidTypeController;
use \App\Http\Controllers\PackageController;
use \App\Http\Controllers\DivisionController;
use \App\Http\Controllers\DistrictController;
use \App\Http\Controllers\UpazilaController;
use \App\Http\Controllers\UnionController;
use \App\Http\Controllers\ItemController;
use \App\Http\Controllers\ItemTypeController;
use \App\Http\Controllers\LotItemAmountController;
use \App\Http\Controllers\InstitutionController;
use \App\Http\Controllers\BivagController;
use \App\Http\Controllers\DepartmentController;
use \App\Http\Controllers\UserController;
use \App\Http\Controllers\DealerController;
use \App\Http\Controllers\Report\ReportController;

//require_once('routes/api.php');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Route::get('/home', [HomeController::class, 'index'])->name('home');


Route::group(['middleware' => ['auth']], function () {
//    Route::get('/', [App\Http\Controllers\HomeController::class, 'cache_clear'])->name('cache_clear');

    //*  Families Route Section */
    Route::post('/families/import', [FamilyController::class, 'import'])->name('families.import');
    Route::post('/families/export', [FamilyController::class, 'export'])->name('families.export');
    Route::get('/families/sampledatadownload', [FamilyController::class, 'sampledatadownload'])->name('families.sampledatadownload');
    Route::post('/families/phoneDuplicateCheck', [FamilyController::class, 'phoneDuplicateCheck'])->name('families.phoneDuplicateCheck');
    Route::post('/families/nidDuplicateCheck', [FamilyController::class, 'nidDuplicateCheck'])->name('families.nidDuplicateCheck');
    Route::post('/families/getFamilyInfo', [FamilyController::class, 'getFamilyInfo'])->name('families.getFamilyInfo');

    Route::post('/family-members/import', [FamilyMemberController::class, 'import'])->name('family-members.import');
    Route::get('/family-members/sampledatadownload', [FamilyMemberController::class, 'sampledatadownload'])->name('family-members.sampledatadownload');
    Route::get('/family-members/shift/{familyId}/{memberId}', [FamilyMemberController::class, 'shift'])->name('family-members.shift');
    Route::post('/family-members/shiftDone', [FamilyMemberController::class, 'shiftDone'])->name('family-members.shiftDone');

    Route::get('family-card/pendingCards', [FamilyCardController::class, 'pendingCards'])->name('family-card.pendingCards');
    Route::post('family-card/generateCardNumbers', [FamilyCardController::class, 'generateCardNumbers'])->name('family-card.generateCardNumbers');
    Route::get('family-card/createCard/{id}/{download?}', [FamilyCardController::class, 'createCard'])->name('family-card.createCard');
    Route::get('family-card/printCards', [FamilyCardController::class, 'printCards'])->name('family-card.printCards');
    Route::post('family-card/chunkCards', [FamilyCardController::class, 'chunkCards'])->name('family-card.chunkCards');
    Route::post('family-card/printCards', [FamilyCardController::class, 'printCards'])->name('family-card.printCards');
    Route::post('packages/getPackageLists', [PackageController::class, 'getPackageLists'])->name('packages.getPackageLists');
    Route::post('packages/getAssignedPackageLists', [PackageController::class, 'getAssignedPackageLists'])->name('packages.getAssignedPackageLists');
    Route::get('packages/bulkAssignPackage', [PackageController::class, 'bulkAssignPackage'])->name('packages.bulkAssignPackage');
    Route::post('packages/saveBulkAssignPackage', [PackageController::class, 'saveBulkAssignPackage'])->name('packages.saveBulkAssignPackage');
    Route::post('packages/assignPackage', [PackageController::class, 'assignPackage'])->name('packages.assignPackage');
    Route::post('packages/unAssignPackage', [PackageController::class, 'unAssignPackage'])->name('packages.unAssignPackage');
    Route::post('item-types/getItemLists', [ItemTypeController::class, 'getItemLists'])->name('item-types.getItemLists');
    Route::post('packages/saveItem', [PackageController::class, 'saveItem'])->name('packages.saveItem');
    Route::post('bivag/bivagSelectAjaxList', [BivagController::class, 'bivagSelectAjaxList'])->name('bivag.bivagSelectAjaxList');
    Route::post('department/deptSelectAjaxList', [DepartmentController::class, 'deptSelectAjaxList'])->name('department.deptSelectAjaxList');
    Route::get('users/changePassword', [UserController::class, 'changePassword'])->name('users.changePassword');
    Route::post('users/updatePassword', [UserController::class, 'updatePassword'])->name('users.updatePassword');
    Route::get('lot-item-amount/add/{packageID}', [LotItemAmountController::class, 'add'])->name('lot-item-amount.add');
    Route::get('lot-item-amount/edit/{packageID}/{lotId}', [LotItemAmountController::class, 'edit'])->name('lot-item-amount.edit');
    Route::post('lot-item-amount/saveLot/{id?}', [LotItemAmountController::class, 'saveLot'])->name('lot-item-amount.saveLot');
    Route::post('dealers/resetPassword/{id}', [DealerController::class, 'resetPassword'])->name('dealers.resetPassword');
    Route::post('dealers/getDealerLists', [DealerController::class, 'getDealerLists'])->name('dealers.getDealerLists');
    Route::post('dealers/getDealerModuleLists', [DealerController::class, 'getDealerModuleLists'])->name('dealers.getDealerModuleLists');
    Route::post('dealers/saveDealer', [DealerController::class, 'saveDealer'])->name('dealers.saveDealer');
    Route::post('dealers/getAssignDealerList', [DealerController::class, 'getAssignDealerList'])->name('dealers.getAssignDealerList');
//    Route::get('users/profile', [UserController::class, 'profile'])->name('users.deptSelectAjaxList');
//    Route::get('users/profile', [UserController::class, 'profile'])->name('users.deptSelectAjaxList');

    //*  District Route Section */
    Route::post('district/districtSelectAjaxList', '\App\Http\Controllers\DistrictController@districtSelectAjaxList')->name('district.districtSelectAjaxList');    // Ajax District List

    //*  Upazila-- Route Section */
    Route::post('upazila/upazilaSelectAjaxList', '\App\Http\Controllers\UpazilaController@upazilaSelectAjaxList')->name('upazila.upazilaSelectAjaxList');    // Ajax Upazila List

    //*  Union Route Section */
    Route::post('union/unionSelectAjaxList', '\App\Http\Controllers\UnionController@unionSelectAjaxList')->name('union.unionSelectAjaxList');    // Ajax District List

    /* Report Route */
    Route::get('report/familyReport', [ReportController::class, 'familyReport'])->name('report.familyReport');
    Route::post('report/familySearchData', [ReportController::class, 'familySearchData'])->name('report.familySearchData');
    Route::post('report/exportFamilyReport', [ReportController::class, 'exportFamilyReport'])->name('report.exportFamilyReport');

    Route::get('report/aidReport', [ReportController::class, 'aidReport'])->name('report.aidReport');
    Route::post('report/aidSearchData', [ReportController::class, 'aidSearchData'])->name('report.aidSearchData');
    Route::post('report/aidSearchAidVsFamilyData', [ReportController::class, 'aidSearchAidVsFamilyData'])->name('report.aidSearchAidVsFamilyData');
    Route::post('report/aidSearchAidVsDealerData', [ReportController::class, 'aidSearchAidVsDealerData'])->name('report.aidSearchAidVsDealerData');
    Route::post('report/aidSearchAidVsPackageData', [ReportController::class, 'aidSearchAidVsPackageData'])->name('report.aidSearchAidVsPackageData');
    Route::post('report/exportAidReport', [ReportController::class, 'exportAidReport'])->name('report.exportAidReport');

    Route::get('report/packageReport', [ReportController::class, 'packageReport'])->name('report.packageReport');
    Route::post('report/packageSearchData', [ReportController::class, 'packageSearchData'])->name('report.packageSearchData');
    Route::post('report/exportPackageReport', [ReportController::class, 'exportPackageReport'])->name('report.exportPackageReport');

    Route::get('report/dealerReport', [ReportController::class, 'dealerReport'])->name('report.dealerReport');
    Route::post('report/dealerSearchData', [ReportController::class, 'dealerSearchData'])->name('report.dealerSearchData');
    Route::post('report/exportDealerReport', [ReportController::class, 'exportDealerReport'])->name('report.exportDealerReport');


    /* Cron Tasks Routes */
    Route::get('cron/test', [FamilyMemberController::class, 'cronTest'])->name('cron.cronTest');


    /*  Resource Route  */
    Route::resource('users', \App\Http\Controllers\UserController::class);
    Route::resource('roles', \App\Http\Controllers\RoleController::class);
    Route::resource('permissions', \App\Http\Controllers\PermissionController::class);
    Route::resource('families',FamilyController::class);
    Route::resource('drags',DragController::class);
    Route::resource('family-members',FamilyMemberController::class);
    Route::resource('aid-types',AidTypeController::class);
    Route::resource('packages',PackageController::class);
    Route::resource('divisions',DivisionController::class);
    Route::resource('districts',DistrictController::class);
    Route::resource('upazillas',UpazilaController::class);

app/Models/FamilyMember.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FamilyMember extends Model
{
    use HasFactory;

    protected $fillable = [
        'family_id',
        'card_no',
        'member_data',
        'm_name',
        'm_dob',
        'm_gender',
        'm_nid',
        'm_phone',
        'm_occupation',
        'm_relation',
        'm_ssnp',
        'm_edu_level',
        'total_member',
        'total_male',
        'total_female',
        'total_others',
        'total_child',
        'status',
    ];

    public function family()
    {
        return $this->belongsTo(Family::class, 'family_id');
    }
}

resources/views/family-members/index.blade.php
@extends('layouts.app')
@section('content-header')
    <h3>পরিবার ম্যানেজমেন্ট</h3>
@endsection
@section('title')
    {{ $page_title }}
@endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 card-primary">
                    <div class="card">
                        <div class="card-header">
                            <h1 class="card-title"> পরিবারের সদস্যদের তালিকা আপলোড </h1>
                        </div>
                        @can('family-excel-import')
                            <div class="card-body">
                                @if(session()->has("failures"))

                                    @if(!empty(session()->get('failures')))
                                        <table class="table table-danger">
                                            <tr>
                                                <th colspan="4">ভুল তালিকা</th>
                                            </tr>
                                            <tr>
                                                <th>নং</th>
                                                <th>পারিবারিক কার্ড নং</th>
                                                <th>এরর মেসেজ</th>
                                            </tr>
                                            <?php $count = 0;
//                                            pr(session()->get('failures'));
                                            ?>
                                            @foreach(session()->get('failures') as $cardId =>$error)
<!--                                                --><?php //pr($error); ?>
                                                @foreach($error as $e)
                                                    <tr>
                                                        <td>{{ $count++ }}</td>
                                                        <td>{{ $cardId }}</td>
                                                        <td>
                                                            {{ $e }}
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            @endforeach

                                        </table>
                                    @endif
                                @endif
                                <form action="{{ route('family-members.import') }}" method="POST"
                                      enctype="multipart/form-data">
                                    @csrf
                                    <div class="row">
                                        <div class="col-md-6">
                                            {{--                                            <div class="form-group">--}}
                                            {{--                                                <div class="input-group">--}}
                                            {{--                                                    <div class="custom-file">--}}
                                            {{--                                                        <input type="file" class="custom-file-input"--}}
                                            {{--                                                               id="exampleInputFile">--}}
                                            {{--                                                        <label class="custom-file-label" for="exampleInputFile">Choose--}}
                                            {{--                                                            file</label>--}}
                                            {{--                                                    </div>--}}
                                            {{--                                                </div>--}}
                                            {{--                                            </div>--}}


                                            <div class="form-group">
                                                <div class="custom-file text-left input-group">
                                                    <input type="file" name="file" class="custom-file-input"
                                                           id="customFile" onchange="javascript:updateList()">
                                                    <label class="custom-file-label" for="customFile">ফাইল বাছাই
                                                        করুন</label>
                                                </div>
                                                <div id="fileList"></div>
                                                {{--                                                @error('file')--}}
                                                {{--                                                <span class="invalid-feedback" role="alert">--}}
                                                {{--                                                    <strong>{{ $message }}</strong>--}}
                                                {{--                                                </span>--}}
                                                {{--                                                @enderror--}}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <button class="btn btn-primary">ফাইল আপলোড</button>
                                                {{--                                <a class="btn btn-success" href="{{ route('families.export') }}">Export data</a>--}}
                                                <a class="btn btn-success"
                                                   href="{{ asset('family_member_sample_data.xlsx') }}">সেম্পল
                                                    ডাটা
                                                    ফাইল ডাউনলোড</a>

                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        @endcan
                        <hr/>

                        {{--                        <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-xl">--}}
                        {{--                            Launch Extra Large Modal--}}
                        {{--                        </button>--}}
                    </div>

                {{--                    <div class="card">--}}

                <!-- /.modal -->
                    {{--                    </div>--}}
                </div>
            </div>
        </div>
    </section>
@endsection
@section('custom_script')
    <script type="text/javascript">
        $(document).ready(function () {

            $("#assign-package").on('click', function (e) {
                e.preventDefault();
                var familyId = $(this).attr('family_id');
                var packageId = $('#package').val();
                // var divId = $(this).attr('id');
                var token = $("input[name='_token']").val();
                var url = "{{ route('packages.assignPackage') }}";

                $.ajax({
                    url: url,
                    method: 'POST',
                    data: {familyId: familyId, packageId: packageId, _token: token},
                    dataType: "json",
                    success: function (data) {
                        console.log(data);
                        window.location.reload();

                        // $('select[name="package"]').empty();
                        // $('select[name="package"]').append('<option value="">' + "--- বাছাই করুন ---" + '</option>');
                        // $.each(data.packageList, function (key, value) {
                        //     $('select[name="package"]').append('<option value="' + key + '">' + value + '</option>');
                        // });
                        // $("#assign-package").attr('family_id', data.family_id);
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        alert("Status: " + textStatus);
                        alert("Error: " + errorThrown);
                        console.log(XMLHttpRequest);
                        console.log(textStatus);
                        console.log(errorThrown);
                        window.location.reload();
                    }
                });
            })

            $("#modal-lg").on("show.bs.modal", function (e) {
                var id = $(e.relatedTarget).data('target-id');
                // var divId = $(this).attr('id');
                var token = $("input[name='_token']").val();
                var url = "{{ route('packages.getPackageLists') }}";

                $.ajax({
                    url: url,
                    method: 'POST',
                    data: {id: id, _token: token},
                    dataType: "json",
                    success: function (data) {
                        console.log(data);

                        $('select[name="package"]').empty();
                        $('select[name="package"]').append('<option value="">' + "--- বাছাই করুন ---" + '</option>');
                        $.each(data.packageList, function (key, value) {
                            $('select[name="package"]').append('<option value="' + key + '">' + value + '</option>');
                        });
                        $("#assign-package").attr('family_id', data.family_id);
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        alert("Status: " + textStatus);
                        alert("Error: " + errorThrown);
                        console.log(XMLHttpRequest);
                        console.log(textStatus);
                        console.log(errorThrown);
                    }
                });

                {{--$.get( "/controller/" + id, function( data ) {--}}
                {{--    $(".modal-body").html(data.html);--}}
                {{--});--}}

            });

            $(document).on("click", "a.delete-family", function (ev) {
                ev.preventDefault();
                let url = $(this).attr("href");
                let id = $(this).attr("id");
                if (confirm("আপনি কি তথ্য মুছে ফেলতে চান?")) {
                    $.ajax({
                        type: 'DELETE',
                        url: url,
                        dataType: 'json',
                        headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                        data: {id: id, "_token": "{{ csrf_token() }}"},

                        success: function (data) {
                            if (data.status == 'success') {
                                window.location.reload();
                            } else if (data.status == 'error') {
                            }
//                    data.request->session()->flash('status', 'Task was successful!');
//                    setInterval(function() {
//                    }, 5900);
                        },
                        error: function (data) {
                        }
                    });

                } else {
                    return false;
                }
            });

            $(function () {
                var table = $('.data-table').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: "{{ route('families.index') }}",
                    columns: [
                        {data: 'card_no', name: 'card_no'},
                        {data: 'name', name: 'name'},
                        {data: 'f_h_name', name: 'f_h_name'},
                        {data: 'phone', name: 'phone'},
                        {data: 'nid', name: 'nid'},
                        {data: 'address', name: 'address'},
                        {data: 'dob', name: 'dob'},
                        {data: 'gender', name: 'gender'},
                        {data: 'action', name: 'action', orderable: false, searchable: false},
                    ]
                });
            });

            $('#customFile').on('change', function () {
                var input = $('#customFile').val();
                $('#fileList').text(input);
            });
        });
    </script>
@endsection